### ISSUE TITLE
Any solution?

### ISSUE THREAD

**Issue by bernardopg** [rohankishore/CashFlow#3]
```
PS C:\Users\berna\Downloads\CashFlow-main>  c:; cd 'c:\Users\berna\Downloads\CashFlow-main'; & 'c:\Users\berna\AppData\Local\Programs\Python\Python312\python.exe' 'c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '54337' '--' 'C:\Users\berna\Downloads\CashFlow-main\CashFlow\main.py' 
Traceback (most recent call last):
  File "c:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\berna\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\berna\.vscode-insiders\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\berna\Downloads\CashFlow-main\CashFlow\main.py", line 178, in <module>
    qdarktheme.setup_theme("dark")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qdarktheme' has no attribute 'setup_theme'
```
____________________________________________________________________________________________________________________________
```
Package                       Version
----------------------------- ---------------
pip                              23.3.2
PyQt5                         5.15.10
PyQt5-Qt5                  5.15.2
PyQt5-sip                   12.13.0
PyQt6                          6.6.1
PyQt6-Qt6                   6.6.1
PyQt6-sip                     13.6.0
pyqtdarktheme             0.1.7
PyQtWebEngine            5.15.6
PyQtWebEngine-Qt5    5.15.2
PySide6                         6.6.1
PySide6-Addons            6.6.1
PySide6-Essentials         6.6.1
QDarkStyle                    3.2.3
qstylizer                         0.2.2
QtAwesome                  1.3.0
qtconsole                       5.5.1
QtPy                          2.4.1
```

**Comment by rohankishore** [comment]
![image](https://github.com/rohankishore/CashFlow/assets/109947257/43b40d22-a170-4fad-856a-8f3fa8ddb7b4)

I'm making the shift to material design to address the issues. Above is the current progress. Thanks, The code will be updated soon.
